name: Generate Contribution Snake
on:
  schedule:
    - cron: "0 0 * * *"  # 每天零点自动更新
  workflow_dispatch:     # 支持手动一键运行
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
